[workspace]
authors = ["harinibaskar <hbaskar@calpoly.edu>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "life"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.4.0.dev2025060513,<26"
